name: Cypress Tests

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    name: Build and test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
      - run: npm ci
      - run: npm run build
      - run: npm run test